// Generated by Xata Codegen 0.29.4. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "friendviews",
    columns: [
      {
        name: "category",
        type: "text",
        notNull: true,
        defaultValue: "general",
      },
      { name: "reviewBody", type: "text" },
      { name: "title", type: "text", notNull: true, defaultValue: "title" },
      {
        name: "authorName",
        type: "text",
        notNull: true,
        defaultValue: "authorName",
      },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Friendviews = InferredTypes["friendviews"];
export type FriendviewsRecord = Friendviews & XataRecord;

export type DatabaseSchema = {
  friendviews: FriendviewsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Kyle-Kelley-s-workspace-8qp0rn.us-east-1.xata.sh/db/friendviews",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
